aplications/persona/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
      path(
        '', 
        views.InicioView.as_view(),  
        name='inicio de nuetsra pagina'
         ),
    path(
        'listar-todo_empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
         ),
    path('lista_area/<shorname>/',
     views.ListByAreaempleado.as_view(),
         name='empleados_area'
         ),
    path('lista-empleados-admin/',
     views.ListaEmpleadoAdmin.as_view(),
         name='empleados_admin'
         ),
    path('buscar_empleado/', views.listEmpleadosBykword.as_view()),
    path('lista-habilidades-empleados/', views.LisHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    path('add-empleado/',
          views.EmpleadoCreateView.as_view(),
          name='empleado_add'
          ),
    path(
        'success/', 
        views.SuccessView.as_view(),  
        name='correcto'
        ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),  
        name='modificar-empleado'
        ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),  
        name='eliminar-empleado'
        ),

]

tienda/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, re_path, include
from aplications.home. views import IndexView
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('aplications.home.urls')),
    re_path('', include('aplications.persona.urls')),
    re_path('', include('aplications.departamento.urls')),
] 

aplications/persona/models.py
#import cmath
#from distutils.command.upload import upload
#from email.mime import image
#from msilib import FCICreate
#from pickle import TRUE
#from tabnanny import verbose
#from tkinter import FIRST
from django.db import models

from aplications.departamento.models import Departamento

# Createur models here.


#from ckeditor.fields import RichTextField
# Create your models here.


class Habilidades(models.Model):
    habilidad = models.CharField('habilidad', max_length=50)
    class meta:
        verbose_name = 'Habilidad'
        verbose_name_plural  = 'Habilidades Empleado'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad

class Empleado(models.Model):
    JOB_CHOICES = {
        ('0', 'CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','VENTAS'),
        ('4','SEGURIDAD'),
        ('5','DIRECTOR EJECUTIVO'),
        ('6','DIRECTOR DE OPÉRACIONES'),
        ('7','DIRECTOR COMERCIAL'),
        ('8','DIRECTOR MARKETING'),
        ('9','DIRECTOR DE RECURSOS HUMANOS'),
        ('10','DIRECTOR FINANCIERO'),
        ('11','SISTEMA'),
        ('12','OTRO'),
    }
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombres Completos', max_length=120, blank=True)
    job = models.CharField('trabajo', max_length=20, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)

    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural   = 'Empleados de la empresa'
        ordering = ['-first_name','last_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name


        

aplications/persona/forms.py
#from pyclbr import Class
#from socket import fromshare
#from tkinter import Widget
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'habilidades',
        )
        widgets = { 
            'habilidades' : forms.CheckboxSelectMultiple()
        }

aplications/persona/views.py
#from cgi import print_form
#from dataclasses import dataclass
#from multiprocessing.heap import Arena
from re import template
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import(ListView,DetailView,CreateView,TemplateView,UpdateView,DeleteView)
from aplications import departamento

from aplications.departamento.models import Departamento
from .models import Empleado
from .forms import EmpleadoForm
# Create your views here.

class InicioView(TemplateView):
    """ Vista que carga la pagina de inico """
    template_name = 'inicio.html'
    

class ListAllEmpleados(ListView):
    template_name = 'persona/lista_all.html'
    paginate_by = 3
    ordering = 'first_name'
    #model = Empleado
    context_object_name = 'listaa'

    def get_queryset(self):
        #print('**********')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
            #first_name=palabra_clave
        )
        return lista

class ListByAreaempleado(ListView):
    #Lista de empleados de una are
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista


class ListaEmpleadoAdmin(ListView):
    #Lista de empleados de una are
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

class listEmpleadosBykword(ListView):
    template_name = 'persona/by_world.html'
    #paginate_by = 4
    #ordering = ''
    context_object_name = 'Empleados'

    def get_queryset(self):
        print('**********')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista

class LisHabilidadesEmpleados(ListView):
    template_name= 'persona/habilidades.html'
    context_object_name = 'Habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=4)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwarg):
        context = super(EmpleadoDetailView, self).get_context_data(**kwarg)
        context['Titulo'] = 'Empleado del mes'
        return context


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name 
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)      


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post (self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    template_name = "persona/delete.html"
    model =Empleado
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Registar Nuevo empleado
{% endblock title %}
    Registar Nuevo empleado


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">REGISTAR NUEVO EMPLEADO</h1>
            <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form_data">{% csrf_token %}

                 <div class="medium-6 cell">
                     <label>Nombres:
                         {{form.first_name}}
                    </label>
                 </div>
                     <div class="medium-6 cell">
                     <label>Apellidos:
                         {{form.last_name}}
                    </label>
                 </div>
                 <div class="medium-6 cell">
                     <label>Trabajo:
                            {{form.job}}
                    </label>
                 </div>
                 <div class="medium-6 cell">
                     <label>Departamento:
                            {{form.departamento}}
                    </label>
                 </div>
                 <div class="medium-6 cell">
                     <label>Habilidades:
                            {{form.habilidades}}
                    </label>
                 </div>
                 <div class="medium-12 cell">
                    <button type="submit" class="button succes" alert>Guardar</button>
                 </div>
            </form>
        </div>
    </div>
  
{% endblock content %}

templates/persona/by_world.html
<h1>Buscar empleados por palabra clave</h1>
{% load static %}
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Imgrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3> Lista resultados</h3>
<ul>
    
    {% for e in Empleados  %}
         <li>{{e}} </li>
        
    {% endfor %}
</ul>

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
      Eliminar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
<div class="grid-x">
    <h1 class="cell">ELIMINAR EMPLEADO: {{object.full_name}}</h1>

     <form class="cell" method="POST">{% csrf_token %}

         <div class="callout secondary">
             <h5>Desea eliminar este empleado</h5>
              <p>Al elminar se borrara todo los datos del empleado</p>
              <button class="button alert">Comfirmar</button>
            </div>
       </form>
    </div>
</div>
{% endblock content %}
    
    

templates/persona/detail_empleado.html
{% extends 'base.html' %}


{% block title %}
      {{ object.full_name }}
{% endblock title %}
      
{% block content %} 
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
<div class="cell large-2 card" style="width: 300px; margin-top: 90px;">
    <div class="card-divider">
     {{ empleado.get_job_display }}
   </div>
    <div class="card-section">
    <h4>{{ empleado.full_name }} </h4>
    <p>{{ empleado.last_name }} </p>
    <p>{{ empleado.departamento.shor_name }} </p>
    <p><samp class="label">HABILIDADES</samp></p>
    <ul class="vertical menu">
         
         {% for h in empleado.habilidades.all  %}
             <li>{{ h.habilidad }}</li>
         {% endfor %}
          

    </ul>
    <p>{{ empleado.habilidades }} </p>
  </div>
</div>
</div>
</div>
{% endblock content %}

templates/persona/habilidades.html
<h1>Habilades de empleado</h1>
<ul>
    
    {% for h in habilidades %}
         <li>{{h}} </li>
        
    {% endfor %}
        
</ul>

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
      Lista de empleados por departamentos
{% endblock title %}
      
{% block content %} 
{% include 'includes/header.html' %}

 <div class="grid-container">
      <div class="grid-x">
            <div class="cell"><h1>EMPLEADO POR AREA</h1></div>
            <div class="cell"></div>
            <table>
                  <thead>
                      <tr>
                      <th width="100">ID</th>
                      <th width="100">NOMBRES</th>
                      <th width="100">APELLIDOS</th>
                      <th width="100">DEPARTAMENTO</th>
                      <th width="100">ACCION</th>
                      </tr>
                   </thead>
                   <tbody>
                       {% for e in object_list  %}
                       <tr>
                           <td>{{ e.id }} </td>
                           <td>{{ e.first_name }}</td>
                           <td>{{ e.last_name }}</td>
                           <td>{{ e.departamento }}</td>
                           <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">VER</a></td>
                       </tr>
                       {% endfor %}
                  </tbody>
              </table>
      </div>
 </div>
{% endblock content %}

templates/persona/lista_all.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">  
     <div class="grid-x">
         <h1 class="cell ">LISTA EMPLEADOS</h1>
         <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
         <div class="cell large-7">
          <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
         </div>
         <div class="cell large-2">
            <button type="submit"class="success button">Buscar</button>
         </div>
     </form>
     <div class="cell">
         <table>
             <thead>
                <tr>
                <th width="100">ID</th>
                <th width="100">NOMBRES</th>
                <th width="100">APELLIDOS</th>
                <th width="100">DEPARTAMENTO</th>
                <th width="100">ACCION</th>
                </tr>
             </thead>
             <tbody>
                 {% for e in object_list %}
                 <tr>
                     <td>{{ e.id }} </td>
                     <td>{{ e.first_name }}</td>
                     <td>{{ e.last_name }}</td>
                     <td>{{ e.departamento }}</td>
                     <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">VER</a></td>
                 </tr>
                 {% endfor %}
            </tbody>
        </table>       
    </div>
    <div class="cell">
         {% if is_paginated %}
         <nav aria-label="Pagination">
             <ul class="pagination">
                 {% if page_obj.has_previous %}
                 <li class="pagination-previous">
                     <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                 </li>
                 {% endif %}
                
                
                 {% for  pagina in paginator.page_range %}

      
                 {% if pagina == page_obj.number %}
                 <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }} </li> 
                 {% else %} 
                 <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li> 
                 {% endif %} 
                 {% endfor %} 
                 

                 {% if page_obj.has_next %}
                 <li class="pagination-next">
                 <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                 </li>
                 {% endif %}
             </ul>
             </nav>   
             {% endif %}
             </div>
         </div>
     </div>
 </div>>
{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">  
    <div class="grid-x">
        <h1 class="cell ">LISTA EMPLEADO</h1>
    <div class="cell">
        <table>
            <thead>
                <tr>
                <th width="100">ID</th>
                <th width="100">NOMBRES</th>
                <th width="100">APELLIDOS</th>
                <th width="100">DEPARTAMENTO</th>
                <th width="100">ACCION</th>
                </tr>
            </thead>
            <tbody>
                 {% for e in object_list %}
                 <tr>
                     <td>{{ e.id }} </td>
                     <td>{{ e.first_name }}</td>
                     <td>{{ e.last_name }}</td>
                     <td>{{ e.departamento }}</td>
                     <td><a class="button success" href="{% url 'persona_app:modificar-empleado' e.id %}">EDITAR</a></td>
                     <td><a class="button alert" href="{% url 'persona_app:eliminar-empleado' e.id %}">ELIMINAR</a></td>
                 </tr>
                 {% endfor %}
            </tbody>
        </table>       
    </div>
</div>
</div>>

    <div class="cell">
     
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
                 {% if page_obj.has_previous %}
                 <li class="pagination-previous">
                     <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                 </li>
                 {% endif %}
                
                
                 {% for  pagina in paginator.page_range %}

      
                 {% if pagina == page_obj.number %}
                 <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }} </li> 
                 {% else %} 
                 <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li> 
                 {% endif %} 
                 {% endfor %} 
                 

                 {% if page_obj.has_next %}
                 <li class="pagination-next">
                 <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                 </li>
                 {% endif %}
            </ul>
          </nav>   
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h1>Felicitaciones se guardo correctamente</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
   Editar Empleado 
{% endblock title %}


{% block content %}
     {% include 'includes/header.html' %}
     <div class="grid-container">
     <div class="grid-x">
        <h1 class="cell">
            MODIFICAR DATOS DEL EMPLEADO
        </h1>
     <form method="POST">{% csrf_token %}
     {{ form.as_p}}
     <button class="button alert">Actualizar</button>
    </form>
   </div>
</div>
{% endblock content %}
    