aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
     path('departamento_lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
     path('neew-departamento/', views.NewDepartamentoView.as_view(), name='nuevo-departamento'),
     
  
]

aplications/persona/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
      path(
        '', 
        views.InicioView.as_view(),  
        name='inicio de nuetsra pagina'
         ),
    path(
        'listar-todo_empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
         ),
    path('lista_area/<shorname>/',
     views.ListByAreaempleado.as_view(),
         name='empleados_area'
         ),
    path('lista-empleados-admin/',
     views.ListaEmpleadoAdmin.as_view(),
         name='empleados_admin'
         ),
    path('buscar_empleado/', views.listEmpleadosBykword.as_view()),
    path('lista-habilidades-empleados/', views.LisHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    path('add-empleado/',
          views.EmpleadoCreateView.as_view(),
          name='empleado_add'
          ),
    path(
        'success/', 
        views.SuccessView.as_view(),  
        name='correcto'
        ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),  
        name='modificar-empleado'
        ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),  
        name='eliminar-empleado'
        ),

]

tienda/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, re_path, include
from aplications.home. views import IndexView
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('aplications.home.urls')),
    re_path('', include('aplications.persona.urls')),
    re_path('', include('aplications.departamento.urls')),
] 

templates/includes/header.html
<div class="top-bar stacked-for-medium">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">EMPLEADO</li>
        <li>
          <a href="{% url 'persona_app:empleados_all' %}">LISTAR</a>
          <!-- <ul class="menu vertical" > -->
            <!-- <li><a href="#">1</a></li> -->
            <!-- <li><a href="#">2</a></li> -->
            <!-- <li><a href="#">3</a></li> -->
          <!-- </ul> -->
        </li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">DEPARTAMENTO</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">ADMINISTRAR</a></li>
        <li><a href="{% url 'departamento_app:nuevo-departamento' %}">NUEVO DEPARTAMENTO</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <!-- <li><input type="search" placeholder="BUSCAR EMPLEADO"></li> -->
        <li><a href="{% url 'persona_app:empleado_add' %}"  class="button">REGISTAR NUEVO EMPLEADO</a></li>
      </ul>
    </div>
  </div>