aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
     path('departamento_lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
     path('neew-departamento/', views.NewDepartamentoView.as_view(), name='nuevo-departamento'),
     
  
]

aplications/persona/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
      path(
        '', 
        views.InicioView.as_view(),  
        name='inicio de nuetsra pagina'
         ),
    path(
        'listar-todo_empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
         ),
    path('lista_area/<shorname>/',
     views.ListByAreaempleado.as_view(),
         name='empleados_area'
         ),
    path('lista-empleados-admin/',
     views.ListaEmpleadoAdmin.as_view(),
         name='empleados_admin'
         ),
    path('buscar_empleado/', views.listEmpleadosBykword.as_view()),
    path('lista-habilidades-empleados/', views.LisHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    path('add-empleado/',
          views.EmpleadoCreateView.as_view(),
          name='empleado_add'
          ),
    path(
        'success/', 
        views.SuccessView.as_view(),  
        name='correcto'
        ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),  
        name='modificar-empleado'
        ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),  
        name='eliminar-empleado'
        ),

]

tienda/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, re_path, include
from aplications.home. views import IndexView
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('aplications.home.urls')),
    re_path('', include('aplications.persona.urls')),
    re_path('', include('aplications.departamento.urls')),
] 

aplications/departamento/models.py
from django.db import models

# Create your models here.


class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre corto', max_length=50, unique=True)
    anulate = models.BooleanField('Anulado', default=False)
 
  
 

    #class Meta:
     #   verbose_name = 'Mi Departamento'
     #   verbose_name_plural = 'Areas de la empresa'
     #   ordering = ['-name']
     #   unique_together = ('name', 'shor_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name  

aplications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    Nombre = forms.CharField(max_length=50)
    Apellidos = forms.CharField(max_length=50)
    Departamento = forms.CharField(max_length=50)
    Shorname= forms.CharField(max_length=20)

aplications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from aplications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm

# Create your views here.


class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'
    

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):

        depa = Departamento(
            name=form.cleaned_data['Departamento'],
            shor_name=form.cleaned_data['Shorname']
        )
        depa.save()

        nombre = form.cleaned_data['Nombre']
        apellido = form.cleaned_data['Apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '10',
            departamento=depa,
     
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Lista departamento
{% endblock title %}


{% block content %}
    {% include "includes/header.html" %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">LISTA DEPARTAMENTO</h1>
        <div class="cell">
            <table>
                <tbody>
                     {% for departamento in departamentos %}
                    <tr>
                         <td>{{ departamento.name }}</td>
                         <td>{{ departamento.shor_name }}</td>
                         <td>
                            <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name  %} ">Ver Empleados</a>
                        </td>
                    </tr>
                     {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}
    
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Reegistrar Departamento
{% endblock title %}
 

{% block content %}
    {% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">REGISTAR DEPARTAMENTO</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
        <div class="medium-6 cell">
            <label>Nombres
                {{form.Nombre}}
            </label>
        <div class="medium-6 cell">
            <label>Apellidos
                {{form.Apellidos}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Departamento
                {{form.Departamento}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Nombre Corto
                {{form.Shorname}}
            </label>
        </div>
        <div class="medium-12 cell">
            <button type="submit" class="button succes" alert>Guardar</button>
        </div>
    </form>
      </div>
    </div>
</div>
{% endblock content %}